### ISSUE TITLE
question: can this be used in Moodle 4 standard?

### ISSUE THREAD

**Issue by Beansworthy** [moodleworkplace/moodle-format_wplist#1]
as above

**Comment by odeialba** [comment]
It would work, but if you were not using this course format in Workplace 3.11, we do not recommend to install it. We suggest you use standard format "Topics" instead. It looks almost the same in 4.0 and has even more features such as course index.

**Comment by marinaglancy** [comment]
Hello! This is covered by the [README](https://github.com/moodleworkplace/moodle-format_wplist/blob/master/README.md) file shipped with this plugin.

Yes it works on Moodle 4 LMS but we do not advise to use it since it has less features than Topics format and is maintained for bug fixes only.

**Comment by marinaglancy** [comment]
jinx, Odei :)
